spring:
  application:
    name: eureka-server

server:
  port: 9002

# 其他EurekaServer的端口
other:
  port: 9001

# 配置EurekaServer
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 是否将自己注册到注册中心,默认为true
    register-with-eureka: true
    # 是否从Eureka中获取注册信息,默认为true
    fetch-registry: true
    # EurekaClient的请求地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 自我保护,默认为开启,开发阶段关闭
    enable-self-preservation: false
    # 剔除服务间隔,默认60s
    eviction-interval-timer-in-ms: 5000