spring:
  application:
    name: eureka-server-slave

  security:
    user:
      name: root
      password: root

server:
  port: 9002

# 配置EurekaServer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    # 是否将自己注册到注册中心,默认为true
    register-with-eureka: true
    # 是否从Eureka中获 取注册信息,默认为true
    fetch-registry: true
    # EurekaClient的请求地址
    service-url:
      defaultZone: http://root:root@127.0.0.1:9001/eureka/,http://root:root@127.0.0.1:9002/eureka/
  server:
    # 自我保护,默认为开启,开发阶段关闭
    enable-self-preservation: false
    # 剔除服务间隔,默认60s
    eviction-interval-timer-in-ms: 5000